"""empty message

Revision ID: 85cea84e76b8
Revises: 6849c90d4062
Create Date: 2024-07-19 16:15:56.613114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cea84e76b8'
down_revision = '6849c90d4062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
